[build]
  command = "echo 'Build completo'"
  publish = "/"
  functions = "functions/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#custom"
  targetPort = 8000
  command = "gunicorn app:app --timeout 120 --bind 0.0.0.0:8000"